return PlaceObj('ModDef', {
	'title', "Rato Dev",
	'dependencies', {},
	'id', "WxLXvdc",
	'author', "rato",
	'version', 574,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/ForceDev.lua",
		"Code/ForceShowCTH.lua",
		"Code/magazine_check.lua",
		"Code/magazine_build.lua",
		"Code/extract_functions.lua",
		"Code/extract_unit.lua",
		"Code/fix_editor_enemysquads.lua",
		"Code/rew_table_separator.lua",
		"Code/PrintAttack.lua",
		"Code/FirearmExec_debug.lua",
		"Code/CheckIfChangedPatchingMethod.lua",
		"Code/used_comps_brute_TOG.lua",
		"Code/Script1.lua",
		"Code/RATOAI_WORKSHOP.lua",
		"Code/Script.lua",
		"Code/Script3.lua",
		"Code/RATODBG_AIDebugUI.lua",
		"Code/RATOTEL_AITelemetry.lua",
		"Code/Rebuild.lua",
	},
	'default_options', {},
	'saved', 1787455886,
	'code_hash', -2648559196909099921,
	'affected_resources', {},
})